feat: support vls128 for ros2
ros-drivers/velodyne pull request #493
Opened 2022-12-08 16:11 UTC by wep21

ros2 port for #370, #382, #413

2022-12-08 22:08 UTC, JWhitleyWork commented
Has this been tested on real hardware?

2022-12-18 06:11 UTC, wep21 commented
Not yet. I will test on real sensor.

2023-03-17 12:50 UTC, Mtestor commented
I have tested and it doesn't work.

2023-03-17 13:02 UTC, Mtestor requested changes

2023-03-17 13:02 UTC, Mtestor commented on velodyne_pointcloud/params/VLS128.yaml
> +distance_resolution: 0.007
Its 0.004 in the manual user.

2023-03-17 13:02 UTC, Mtestor commented on velodyne_pointcloud/src/lib/rawdata.cpp
> +  float xy_distance;
Won't it better to place the declaration where its used ?

2023-03-18 07:22 UTC, wep21 commented
@Mtestor Thank you for testing. Could you create a PR to my branch?

2023-03-18 13:11 UTC, Mtestor commented
sure

2023-03-18 13:21 UTC, Mtestor commented
@wep21 your branch doesn't appear when i try to pull request.

2023-03-18 13:33 UTC, wep21 commented
@Mtestor You mean you cannot find my branch even when creating a PR from my [fork](https://github.com/wep21/velodyne/pulls)?

2023-03-18 13:49 UTC, Mtestor commented
Thanks ! I have done a PR.

2023-05-28 13:19 UTC, JWhitleyWork commented
Rebased on current `ros2` branch, which includes updated CI job.

2023-05-29 08:35 UTC, JWhitleyWork approved these changes
With rebase and some minor fixes, this looks good!

2023-05-29 08:41 UTC, merged